version: '3.7'
services:
  db:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    restart: always
    networks: ['default']
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
